import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { jobService, resumeService, recommendationService } from '../services/api';
import { 
  Briefcase, 
  FileText, 
  Sparkles, 
  AlertTriangle,
  ArrowRight,
  Cpu,
  BookmarkCheck
} from 'lucide-react';

const Dashboard: React.FC = () => {
  const { currentUser } = useAuth();
  const [stats, setStats] = useState({
    totalJobs: 0,
    resumeUploaded: false,
    resumeName: '',
    parsedSkillsCount: 0,
    recommendationsCount: 0,
    skillsGapCount: 0,
  });
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchDashboardData = async () => {
      try {
        const jobs = await jobService.list();
        const activeResume = await resumeService.getActive().catch(() => null);
        const recommendations = await recommendationService.list().catch(() => []);
        const gapAnalysis = await recommendationService.getSkillsGap().catch(() => null);

        setStats({
          totalJobs: jobs.length,
          resumeUploaded: !!activeResume,
          resumeName: activeResume?.file_name || '',
          parsedSkillsCount: activeResume?.parsed_skills?.length || 0,
          recommendationsCount: recommendations.length,
          skillsGapCount: gapAnalysis?.skill_gaps?.length || 0,
        });
      } catch (error) {
        console.error("Failed to load dashboard statistics:", error);
      } finally {
        setLoading(false);
      }
    };

    fetchDashboardData();
  }, []);

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[60vh]">
        <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-indigo-500"></div>
      </div>
    );
  }

  const statCards = [
    {
      name: 'Active Jobs',
      value: stats.totalJobs,
      description: 'Jobs currently listed in our database.',
      icon: Briefcase,
      color: 'from-blue-500/20 to-cyan-500/10 text-blue-400 border-blue-500/20',
      link: '/jobs',
    },
    {
      name: 'Resume Status',
      value: stats.resumeUploaded ? 'Parsed' : 'Not Uploaded',
      description: stats.resumeUploaded 
        ? `${stats.resumeName} (${stats.parsedSkillsCount} skills found)` 
        : 'Upload your resume to get started.',
      icon: FileText,
      color: stats.resumeUploaded 
        ? 'from-emerald-500/20 to-teal-500/10 text-emerald-400 border-emerald-500/20' 
        : 'from-amber-500/20 to-yellow-500/10 text-amber-400 border-amber-500/20',
      link: '/resumes',
    },
    {
      name: 'AI Recommendations',
      value: stats.recommendationsCount,
      description: 'Matches generated by semantic comparison.',
      icon: Sparkles,
      color: 'from-indigo-500/20 to-purple-500/10 text-indigo-400 border-indigo-500/20',
      link: '/recommendations',
    },
    {
      name: 'Skills Gap Identified',
      value: stats.skillsGapCount,
      description: 'Missing skills across target opportunities.',
      icon: AlertTriangle,
      color: 'from-rose-500/20 to-pink-500/10 text-rose-400 border-rose-500/20',
      link: '/skills-gap',
    },
  ];

  return (
    <div className="space-y-8 animate-fadeIn">
      {/* Welcome Hero */}
      <div className="bg-gradient-to-r from-indigo-900/40 via-purple-900/20 to-slate-900/60 backdrop-blur-md rounded-2xl border border-indigo-500/10 p-6 md:p-8 flex flex-col md:flex-row items-center justify-between gap-6 shadow-xl relative overflow-hidden">
        <div className="absolute top-0 right-0 -mt-8 -mr-8 w-60 h-60 bg-indigo-500/10 rounded-full blur-3xl pointer-events-none"></div>
        <div className="space-y-3 text-center md:text-left relative z-10">
          <h2 className="text-3xl md:text-4xl font-extrabold text-white tracking-tight">
            Hello, <span className="bg-gradient-to-r from-blue-400 to-indigo-400 bg-clip-text text-transparent">{currentUser?.full_name}</span>!
          </h2>
          <p className="text-slate-400 max-w-xl text-sm md:text-base leading-relaxed">
            Welcome to your career command center. Use semantic search and generative AI models to discover targeted opportunities and design learning roadmaps.
          </p>
        </div>
        <div className="flex shrink-0 space-x-3">
          {!stats.resumeUploaded ? (
            <Link
              to="/resumes"
              className="bg-indigo-600 hover:bg-indigo-500 text-white font-semibold px-5 py-3 rounded-xl flex items-center space-x-2 text-sm shadow-lg shadow-indigo-600/20 active:scale-95 transition-all"
            >
              <span>Upload Resume</span>
              <ArrowRight className="h-4 w-4" />
            </Link>
          ) : (
            <Link
              to="/recommendations"
              className="bg-indigo-600 hover:bg-indigo-500 text-white font-semibold px-5 py-3 rounded-xl flex items-center space-x-2 text-sm shadow-lg shadow-indigo-600/20 active:scale-95 transition-all"
            >
              <span>AI Job Matches</span>
              <Sparkles className="h-4 w-4" />
            </Link>
          )}
        </div>
      </div>

      {/* Stats Cards Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
        {statCards.map((card) => {
          const Icon = card.icon;
          return (
            <div 
              key={card.name} 
              className={`bg-slate-900/40 backdrop-blur-md rounded-2xl border p-6 flex flex-col justify-between hover:shadow-lg hover:border-slate-700/50 transition-all group ${card.color.split(' ')[2]}`}
            >
              <div className="flex items-center justify-between mb-4">
                <span className="text-sm font-semibold uppercase tracking-wider text-slate-500">{card.name}</span>
                <div className={`p-2.5 rounded-xl bg-gradient-to-br ${card.color.split(' ')[0]} ${card.color.split(' ')[1]} border border-transparent`}>
                  <Icon className="h-5 w-5" />
                </div>
              </div>
              <div>
                <p className="text-3xl font-extrabold text-white tracking-tight mb-2">{card.value}</p>
                <p className="text-xs text-slate-400 leading-relaxed mb-4 min-h-[32px]">{card.description}</p>
                <Link 
                  to={card.link} 
                  className="text-xs font-semibold text-indigo-400 hover:text-indigo-300 flex items-center space-x-1.5 group-hover:translate-x-1 transition-transform"
                >
                  <span>Explore Details</span>
                  <span>→</span>
                </Link>
              </div>
            </div>
          );
        })}
      </div>

      {/* Secondary Quick Access Block */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left Card: AI Assistant Status */}
        <div className="lg:col-span-2 bg-slate-900/40 backdrop-blur-md rounded-2xl border border-slate-800/80 p-6 flex flex-col justify-between">
          <div className="flex items-center space-x-3 mb-4">
            <Cpu className="h-6 w-6 text-indigo-400" />
            <h3 className="font-bold text-lg text-white">Semantic AI Agent</h3>
          </div>
          <p className="text-sm text-slate-400 leading-relaxed mb-6">
            Your profile has been indexed with SentenceTransformers and is ready for real-time similarity checks. We query Qdrant collection vectors and apply Groq Llama3 analysis models to verify matches and draft skills gap learning paths.
          </p>
          <div className="flex flex-wrap gap-3">
            <div className="bg-slate-950/60 border border-slate-800 px-4 py-2 rounded-xl text-xs flex items-center space-x-2 text-slate-400">
              <span className="h-2 w-2 rounded-full bg-emerald-500"></span>
              <span>Model: Llama3-8b-8192</span>
            </div>
            <div className="bg-slate-950/60 border border-slate-800 px-4 py-2 rounded-xl text-xs flex items-center space-x-2 text-slate-400">
              <span className="h-2 w-2 rounded-full bg-indigo-500 animate-pulse"></span>
              <span>Vector Database: Qdrant</span>
            </div>
            <div className="bg-slate-950/60 border border-slate-800 px-4 py-2 rounded-xl text-xs flex items-center space-x-2 text-slate-400">
              <span className="h-2 w-2 rounded-full bg-blue-500"></span>
              <span>Embeddings: SentenceTransformers</span>
            </div>
          </div>
        </div>

        {/* Right Card: Quick Actions */}
        <div className="bg-slate-900/40 backdrop-blur-md rounded-2xl border border-slate-800/80 p-6 flex flex-col justify-between">
          <div className="flex items-center space-x-3 mb-4">
            <BookmarkCheck className="h-6 w-6 text-purple-400" />
            <h3 className="font-bold text-lg text-white">Quick Tasks</h3>
          </div>
          <div className="space-y-3 mb-6">
            <Link to="/jobs" className="flex items-center justify-between p-3 rounded-xl bg-slate-950/40 hover:bg-slate-950/80 border border-slate-850 hover:border-slate-800 transition-all text-xs font-semibold text-slate-300">
              <span>Add Job Opportunity</span>
              <span>＋</span>
            </Link>
            <Link to="/resumes" className="flex items-center justify-between p-3 rounded-xl bg-slate-950/40 hover:bg-slate-950/80 border border-slate-850 hover:border-slate-800 transition-all text-xs font-semibold text-slate-300">
              <span>View Parser Logs</span>
              <span>➔</span>
            </Link>
          </div>
          <div className="text-center text-xs text-slate-500">
            System uptime is 100%. Data in sync.
          </div>
        </div>
      </div>
    </div>
  );
};

export default Dashboard;
